version: '3'

services:
  db:
    image: mongo
    volumes:
      - ./data:/data/db
      - ./backups:/backups
    networks:
      - mynet
  web:
    image: mulleady1/budgeter:latest
    command: python wsgi.py
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - pnet
      - mynet
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynet
networks:
  mynet: {}
  pnet:
    external:
      name: pnet
