# Generated by Django 5.2.1 on 2025-10-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bill_options_alter_bill_month_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
