# Generated by Django 5.2.1 on 2025-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userprofile_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="autopay",
            field=models.BooleanField(default=False),
        ),
    ]
