# Generated by Django 5.2.1 on 2025-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_billlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billlink',
            options={'ordering': ['sort_order', 'label']},
        ),
        migrations.AddField(
            model_name='billlink',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
