# Generated by Django 5.2.1 on 2025-11-27 02:10

from django.db import migrations


def set_unique_sort_orders(apps, schema_editor):
    """Set unique sort_orders for each user's BillLinks"""
    BillLink = apps.get_model('app', 'BillLink')
    User = apps.get_model('auth', 'User')

    # Process each user's BillLinks separately
    for user in User.objects.all():
        billlinks = BillLink.objects.filter(user=user).order_by('created_at', 'id')
        for index, billlink in enumerate(billlinks):
            billlink.sort_order = index
            billlink.save(update_fields=['sort_order'])


def reverse_sort_orders(apps, schema_editor):
    """Reset all sort_orders to 0"""
    BillLink = apps.get_model('app', 'BillLink')
    BillLink.objects.all().update(sort_order=0)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_billlink_options_billlink_sort_order'),
    ]

    operations = [
        migrations.RunPython(set_unique_sort_orders, reverse_sort_orders),
    ]
