# Generated by Django 5.2.1 on 2025-12-07 22:09

from django.db import migrations


def create_default_categories_and_rules(apps, schema_editor):
    Category = apps.get_model("app", "Category")
    CategoryRule = apps.get_model("app", "CategoryRule")

    # Create default categories
    categories = {}
    for category_code, _ in [
        ("dining", "Dining & Food"),
        ("groceries", "Groceries"),
        ("shopping", "Shopping"),
        ("transportation", "Transportation"),
        ("entertainment", "Entertainment"),
        ("utilities", "Utilities"),
        ("healthcare", "Healthcare"),
        ("travel", "Travel"),
        ("income", "Income"),
        ("other", "Other"),
    ]:
        cat, created = Category.objects.get_or_create(
            name=category_code, user=None, defaults={"is_default": True}
        )
        categories[category_code] = cat

    # Create default category rules
    default_rules = {
        "dining": [
            "restaurant",
            "cafe",
            "coffee",
            "starbucks",
            "dunkin",
            "chipotle",
            "mcdonalds",
            "burger king",
            "wendys",
            "taco bell",
            "subway",
            "pizza",
            "doordash",
            "uber eats",
            "grubhub",
            "postmates",
            "seamless",
            "panera",
            "chick-fil-a",
            "food delivery",
            "dining",
        ],
        "groceries": [
            "whole foods",
            "trader joe",
            "safeway",
            "kroger",
            "walmart",
            "target grocery",
            "albertsons",
            "publix",
            "wegmans",
            "costco",
            "sams club",
            "aldi",
            "grocery",
            "supermarket",
            "food market",
        ],
        "shopping": [
            "amazon",
            "target",
            "best buy",
            "apple store",
            "walmart store",
            "macys",
            "nordstrom",
            "kohls",
            "tj maxx",
            "marshalls",
            "home depot",
            "lowes",
            "ikea",
            "wayfair",
            "etsy",
            "ebay",
        ],
        "transportation": [
            "uber",
            "lyft",
            "shell",
            "chevron",
            "exxon",
            "mobil",
            "bp",
            "arco",
            "parking",
            "metro",
            "transit",
            "bart",
            "mta",
            "gas station",
            "fuel",
        ],
        "entertainment": [
            "netflix",
            "hulu",
            "disney",
            "spotify",
            "apple music",
            "youtube",
            "hbo",
            "amazon prime",
            "movie",
            "theater",
            "cinema",
            "concert",
            "ticketmaster",
            "steam",
            "playstation",
            "xbox",
        ],
        "utilities": [
            "electric",
            "gas bill",
            "water",
            "internet",
            "comcast",
            "att",
            "verizon",
            "tmobile",
            "sprint",
            "phone bill",
            "utility",
        ],
        "healthcare": [
            "pharmacy",
            "cvs",
            "walgreens",
            "rite aid",
            "doctor",
            "dentist",
            "medical",
            "hospital",
            "clinic",
            "health",
        ],
        "travel": [
            "airline",
            "flight",
            "hotel",
            "airbnb",
            "marriott",
            "hilton",
            "hyatt",
            "expedia",
            "booking.com",
            "rental car",
            "hertz",
            "enterprise",
        ],
        "income": [
            "paycheck",
            "salary",
            "deposit",
            "refund",
            "reimbursement",
            "payment received",
        ],
    }

    for category_name, keywords in default_rules.items():
        category = categories.get(category_name)
        if category:
            for keyword in keywords:
                CategoryRule.objects.get_or_create(
                    keyword=keyword.lower(),
                    user=None,
                    category=category,
                    defaults={"is_default": True, "priority": 0},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_categoryrule_budget_transaction'),
    ]

    operations = [
        migrations.RunPython(create_default_categories_and_rules),
    ]
