# Generated by Django 6.0 on 2025-12-11 02:41

from django.db import migrations, models


def set_category_colors(apps, schema_editor):
    """Set colors for existing categories based on their names"""
    Category = apps.get_model('app', 'Category')

    color_map = {
        "dining": "#ff6b6b",
        "groceries": "#4ecdc4",
        "shopping": "#95e1d3",
        "transportation": "#f38181",
        "entertainment": "#aa96da",
        "utilities": "#fcbad3",
        "healthcare": "#a8d8ea",
        "travel": "#ffaaa5",
        "income": "#51cf66",
        "other": "#868e96",
    }

    for category in Category.objects.all():
        if category.name.lower() in color_map:
            category.color = color_map[category.name.lower()]
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20251207_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#9c6ade', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(set_category_colors, migrations.RunPython.noop),
    ]
