# Generated by Django migration on 2025-12-12

from django.db import migrations


def update_category_rules(apps, schema_editor):
    Category = apps.get_model("app", "Category")
    CategoryRule = apps.get_model("app", "CategoryRule")

    # Get the Groceries category
    try:
        groceries_category = Category.objects.get(name="Groceries", user=None)

        # Add new grocery keywords
        new_grocery_keywords = ["foodland", "tokyo central"]
        for keyword in new_grocery_keywords:
            CategoryRule.objects.get_or_create(
                keyword=keyword.lower(),
                user=None,
                category=groceries_category,
                defaults={"is_default": True, "priority": 0},
            )
    except Category.DoesNotExist:
        pass

    # Update walmart keyword in Shopping category
    try:
        shopping_category = Category.objects.get(name="Shopping", user=None)

        # Try to find and update the old "walmart store" rule
        old_walmart_rule = CategoryRule.objects.filter(
            keyword="walmart store",
            user=None,
            category=shopping_category
        ).first()

        if old_walmart_rule:
            # Check if "walmart" already exists
            walmart_exists = CategoryRule.objects.filter(
                keyword="walmart",
                user=None,
                category=shopping_category
            ).exists()

            if not walmart_exists:
                old_walmart_rule.keyword = "walmart"
                old_walmart_rule.save()
            else:
                # If "walmart" already exists, just delete the old one
                old_walmart_rule.delete()
    except Category.DoesNotExist:
        pass


def reverse_update_category_rules(apps, schema_editor):
    CategoryRule = apps.get_model("app", "CategoryRule")
    Category = apps.get_model("app", "Category")

    # Remove the added grocery keywords
    try:
        groceries_category = Category.objects.get(name="Groceries", user=None)
        CategoryRule.objects.filter(
            keyword__in=["foodland", "tokyo central"],
            user=None,
            category=groceries_category
        ).delete()
    except Category.DoesNotExist:
        pass

    # Revert walmart change
    try:
        shopping_category = Category.objects.get(name="Shopping", user=None)
        walmart_rule = CategoryRule.objects.filter(
            keyword="walmart",
            user=None,
            category=shopping_category
        ).first()

        if walmart_rule:
            walmart_rule.keyword = "walmart store"
            walmart_rule.save()
    except Category.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_category_color_alter_category_name"),
    ]

    operations = [
        migrations.RunPython(update_category_rules, reverse_update_category_rules),
    ]
