# Generated by Django 6.0 on 2025-12-13 01:52

from django.db import migrations


def clone_default_categories_and_rules_for_existing_users(apps, schema_editor):
    """Clone default categories and category rules for all existing users"""
    User = apps.get_model("auth", "User")
    Category = apps.get_model("app", "Category")
    CategoryRule = apps.get_model("app", "CategoryRule")

    # Get all default categories
    default_categories = Category.objects.filter(user=None)

    # Process each existing user
    for user in User.objects.all():
        # Skip if user already has personal categories
        if Category.objects.filter(user=user).exists():
            continue

        category_mapping = {}  # Map old category PK to new category

        # Clone default categories for this user
        for default_cat in default_categories:
            new_cat = Category.objects.create(
                name=default_cat.name,
                user=user,
                is_default=False,
                color=default_cat.color,
            )
            category_mapping[default_cat.pk] = new_cat

        # Clone default category rules for this user
        default_rules = CategoryRule.objects.filter(user=None)

        for default_rule in default_rules:
            # Get the user's corresponding category
            new_category = category_mapping.get(default_rule.category_id)
            if new_category:
                CategoryRule.objects.create(
                    user=user,
                    keyword=default_rule.keyword,
                    category=new_category,
                    is_default=False,
                    priority=default_rule.priority,
                )


def reverse_clone(apps, schema_editor):
    """Remove cloned categories and rules for all users"""
    Category = apps.get_model("app", "Category")
    CategoryRule = apps.get_model("app", "CategoryRule")

    # Delete all user-specific categories and rules (but keep defaults)
    CategoryRule.objects.exclude(user=None).delete()
    Category.objects.exclude(user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_update_category_rules'),
    ]

    operations = [
        migrations.RunPython(
            clone_default_categories_and_rules_for_existing_users,
            reverse_clone,
        ),
    ]
