# Generated by Django 6.0 on 2025-12-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_clone_default_rules_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
