# Generated by Django 6.0 on 2025-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_receipt_receiptitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="merchant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
