# Generated by Django 6.0 on 2026-08-12 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_receipt_processing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Produce', 'Produce'), ('Meat & Seafood', 'Meat & Seafood'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Bakery', 'Bakery'), ('Cereal & Breakfast', 'Cereal & Breakfast'), ('Pantry & Dry Goods', 'Pantry & Dry Goods'), ('Snacks & Candy', 'Snacks & Candy'), ('Frozen Foods', 'Frozen Foods'), ('Beverages', 'Beverages'), ('Alcohol', 'Alcohol'), ('Prepared & Deli', 'Prepared & Deli'), ('Baby & Kids', 'Baby & Kids'), ('Health & Pharmacy', 'Health & Pharmacy'), ('Personal Care', 'Personal Care'), ('Household & Cleaning', 'Household & Cleaning'), ('Paper Goods', 'Paper Goods'), ('Pet', 'Pet'), ('Home & Kitchen', 'Home & Kitchen'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Office & School', 'Office & School'), ('Auto & Fuel', 'Auto & Fuel'), ('Garden & Outdoor', 'Garden & Outdoor'), ('Tools & Hardware', 'Tools & Hardware'), ('Entertainment', 'Entertainment'), ('Services & Fees', 'Services & Fees'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.CharField(db_index=True, max_length=500)),
                ('normalized_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(choices=[('Produce', 'Produce'), ('Meat & Seafood', 'Meat & Seafood'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Bakery', 'Bakery'), ('Cereal & Breakfast', 'Cereal & Breakfast'), ('Pantry & Dry Goods', 'Pantry & Dry Goods'), ('Snacks & Candy', 'Snacks & Candy'), ('Frozen Foods', 'Frozen Foods'), ('Beverages', 'Beverages'), ('Alcohol', 'Alcohol'), ('Prepared & Deli', 'Prepared & Deli'), ('Baby & Kids', 'Baby & Kids'), ('Health & Pharmacy', 'Health & Pharmacy'), ('Personal Care', 'Personal Care'), ('Household & Cleaning', 'Household & Cleaning'), ('Paper Goods', 'Paper Goods'), ('Pet', 'Pet'), ('Home & Kitchen', 'Home & Kitchen'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Office & School', 'Office & School'), ('Auto & Fuel', 'Auto & Fuel'), ('Garden & Outdoor', 'Garden & Outdoor'), ('Tools & Hardware', 'Tools & Hardware'), ('Entertainment', 'Entertainment'), ('Services & Fees', 'Services & Fees'), ('Other', 'Other')], default='Other', max_length=50)),
                ('is_user_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Item aliases',
                'ordering': ['raw_description'],
                'unique_together': {('user', 'raw_description')},
            },
        ),
    ]
