# Generated by Django 6.0 on 2026-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_receiptitem_normalized_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemalias',
            name='product_category',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Auto & Fuel', 'Auto & Fuel'), ('Baby & Kids', 'Baby & Kids'), ('Bakery', 'Bakery'), ('Beverages', 'Beverages'), ('Cereal & Breakfast', 'Cereal & Breakfast'), ('Clothing', 'Clothing'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Electronics', 'Electronics'), ('Entertainment', 'Entertainment'), ('Frozen Foods', 'Frozen Foods'), ('Garden & Outdoor', 'Garden & Outdoor'), ('Health & Pharmacy', 'Health & Pharmacy'), ('Home & Kitchen', 'Home & Kitchen'), ('Household & Cleaning', 'Household & Cleaning'), ('Meat & Seafood', 'Meat & Seafood'), ('Office & School', 'Office & School'), ('Other', 'Other'), ('Pantry & Dry Goods', 'Pantry & Dry Goods'), ('Paper Goods', 'Paper Goods'), ('Personal Care', 'Personal Care'), ('Pet', 'Pet'), ('Prepared & Deli', 'Prepared & Deli'), ('Produce', 'Produce'), ('Services & Fees', 'Services & Fees'), ('Snacks & Candy', 'Snacks & Candy'), ('Tools & Hardware', 'Tools & Hardware')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Alcohol', 'Alcohol'), ('Auto & Fuel', 'Auto & Fuel'), ('Baby & Kids', 'Baby & Kids'), ('Bakery', 'Bakery'), ('Beverages', 'Beverages'), ('Cereal & Breakfast', 'Cereal & Breakfast'), ('Clothing', 'Clothing'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Electronics', 'Electronics'), ('Entertainment', 'Entertainment'), ('Frozen Foods', 'Frozen Foods'), ('Garden & Outdoor', 'Garden & Outdoor'), ('Health & Pharmacy', 'Health & Pharmacy'), ('Home & Kitchen', 'Home & Kitchen'), ('Household & Cleaning', 'Household & Cleaning'), ('Meat & Seafood', 'Meat & Seafood'), ('Office & School', 'Office & School'), ('Other', 'Other'), ('Pantry & Dry Goods', 'Pantry & Dry Goods'), ('Paper Goods', 'Paper Goods'), ('Personal Care', 'Personal Care'), ('Pet', 'Pet'), ('Prepared & Deli', 'Prepared & Deli'), ('Produce', 'Produce'), ('Services & Fees', 'Services & Fees'), ('Snacks & Candy', 'Snacks & Candy'), ('Tools & Hardware', 'Tools & Hardware')], db_index=True, max_length=50),
        ),
    ]
