# Generated by Django 6.0 on 2026-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_itemalias_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='receipts/thumbs/%Y/%m/'),
        ),
    ]
